# Generated by Django 5.0.6 on 2024-05-25 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_reseñas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñas',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
