# Generated by Django 5.0.6 on 2024-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_reseñas_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autores_seguidos',
            field=models.ManyToManyField(related_name='seguidores', to='libros.autores'),
        ),
    ]
