# Generated by Django 5.0.6 on 2024-05-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_remove_user_es_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='ano_publicacion',
            field=models.IntegerField(),
        ),
    ]
